import "./sass/style.scss"
import "./sass/extra/materialize/materialize.scss"

import "./js/materialize.min.js"
import "./js/owl-carousel/owl.carousel.min.js"
import "./js/owl-carousel/assets/owl.carousel.min.scss"
import "./js/owl-carousel/assets/owl.theme.default.min.scss"
import "./js/inputmask"
import "./js/sweetalert"
import "./js/rf-admin-scripts"
import "./js/rf-scripts"
import "./js/rf-woo"